<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\VSlices\VSlices.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="LanguageExt.Common" />
		<Using Include="LanguageExt.Traits" />
		<Using Include="LanguageExt.Effects" />

		<Using Include="LanguageExt.Prelude" Static="true" />

		<Using Include="VSlices.Monads" />
		<Using Include="VSlices.Arrows" />

		<Using Include="VSlices.VSlicesPrelude" Static="true" />
	</ItemGroup>
</Project>
